accessKey        = "AKIA2VK6KRT7PA4ZDRKE"
secretKey        = "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"
region           = "us-east-1"
api-gateway-name = "vijaycloudnloudgateway"
vpc_cidr         = "10.0.0.0/16"
project          = "duckduckgo"
key-name         = "xps-add"
